#!/bin/bash

# shellcheck disable=SC2034
SCRIPTPATH="$(
  cd -- "$(dirname "$0")" >/dev/null 2>&1 || exit 1
  pwd -P
)"
SCRIPTNAME="$(basename "$0")"
set -e

init_logger() {
  local log_file="${XDG_CACHE_HOME:-${HOME}/.cache}/snippets/_log.sh"
  local last_download_file="/tmp/_log.time"
  local delai=14400 # 4 hours
  # shellcheck disable=SC2155
  local curr_time=$(date +%s)
  local time="$((curr_time - $(cat "${last_download_file}" 2>/dev/null || echo "0")))"

  if ! [[ -f "${log_file}" ]] ||
    { [[ -f "${log_file}" ]] && [[ "${time}" -gt "${delai}" ]]; }; then
    if ping -q -c 1 framagit.org &>/dev/null; then
      # shellcheck disable=SC1090
      source <(curl -s https://framagit.org/-/snippets/7183/raw/main/_get_log.sh)
      echo "${curr_time}" >"${last_download_file}"
    else
      echo -e "\033[1;33m[WARNING]\033[0;33m Unable to get last logger version, will use \`echo\`.\033[0m"
      _log() {
        # shellcheck disable=SC2317
        echo "$@"
      }
    fi
  else
    # shellcheck disable=SC1090
    source <(cat "${log_file}")
  fi
}

revert() {
  # Revert black screen
  xset dpms 0 0 0
}

exists() {
  local cmd=$1
  if ! command -v "${cmd}" &>/dev/null; then
    _log "ERROR" "Command \`${cmd}\` is required"
    return 1
  fi
}

main() {
  export DEBUG_LEVEL="${DEBUG_LEVEL:-INFO}"
  init_logger

  # Compute randome bluring effect
  local v=$((RANDOM % 25 + 10))
  local h=$((RANDOM % 25 + 10))
  local screen_file="/tmp/screenshot.png"
  local blur_file="/tmp/screenshot_blur.png"

  if ! exists "scrot" || ! exists "convert" || ! exists "i3lock"; then
    exit 1
  fi

  # Take a screenshot
  if [[ -f "${screen_file}" ]]; then
    rm "${screen_file}"
  fi

  scrot "${screen_file}"
  # Blur screenshot
  magick "${screen_file}" -blur ${v}x${h} "${blur_file}"

  if [[ -f "${screen_file}" ]]; then
    rm "${screen_file}"
  fi

  # Setup trap to revert black screen
  trap revert HUP INT TERM
  # Lock screen using i3lock and blur screenshot
  i3lock -i "${blur_file}" -n
}

main
