#!/bin/sh
xrandr \
  --output eDP1 \
    --scale 0.75x0.75 \
    --primary \
    --mode 2256x1504 \
    --pos 820x1080 \
    --rotate normal \
  --output DP1 \
    --mode 1920x1080 \
    --pos 1920x0 \
    --rotate normal \
  --output DP2 \
    --mode 1920x1080 \
    --pos 0x0 \
    --rotate normal \
  --output DP3 \
    --off \
  --output DP4 \
    --off \
  --output VIRTUAL1 \
    --off
echo 'awesome.restart()' | awesome-client > /dev/null 2>&1
