classes: {
  udp: {
    shape: text
  }
  tcp: {
    shape: rectangle
  }
  interface: {
    icon.near: outside-top-left
    shape: rectangle
    style: {
      fill: white
      stroke: blue
    }
    width: 200
  }
  text: {
    shape: rectangle
  }
}
