users:
    rdeville:
        password: ENC[AES256_GCM,data:3ch/ZJdDhuUkliusXvAHzA6wFvHgxPEShMlyIAt32VE3bXVbBmVb2rxOgqaVDOeR/N/FK6UXB2GSEjmp6a/F3tM/WEP6685L2Q==,iv:qNXdNGOzo/HWIp7ZwSq/E+AnSvtqa8bArkbNFRZ0S+g=,tag:bpEoGA0fkT1iQHGx/B+r1w==,type:str]
    root:
        password: ENC[AES256_GCM,data:ZP2AmrYFvNuDOCgf7LiLLkTLfwy8qEUUYB1YVyHpud39Wkg4OQo1wNXvXEl8g220plI3rlXgNZjJkM/5IsTSZrv1evmiNCsRFw==,iv:a2I81ymzjB73ruPXUo9cV9f2NciW13ILktjyxqzzvmE=,tag:PzlQd00SJVk+l9bgHUU3Vg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5w53ch2ym5qmhew239j7qh0q0ax72daq42qvvwexferta2yrprsf4kes9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQWgzbGdFYStWTVZreXlJ
            b2lVYTNTb0txaE5VQ3ZlbWh5QlEzSnR3ZnpJCmdTMWJ1U1REM0ZwWGw0Z2tncGE2
            enB0MmpjRE9CSGc3WGJ3b1RaNlUxTVkKLS0tIEhEdGIxNnl5MXFna0VsazFJL29M
            TndZUzdUeE9aOW9KSUJnZ1JmZTltbWMKKe4pdiya75qSkSUCx53RZ4jqT+oy1gLR
            kLWc8g8w4rfd88wfSuYQDa5bt4vgLgMZ0zKqM5WBwPfi2IUm+NjEig==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f6yc0z336wkj0ac0qhak2u2t5wqaksf8hpgxvn2mtas26hwk5gasx0th2l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3c0prZDh2S3d6eHhZd3pR
            b3c5K3FLV2F4bzFNRnFJK2sycHMvUkxuVVhZCkNDbEJKWUR5OEpCS0JKNHB5SitV
            WGZONVAzTWc2dnNPRkdBQWpxWVduSHcKLS0tIFhZNGZlWDdoRTJkSHJ1cXBmdFFa
            cEhIMUNhTk5mc0QrZ3FjZXBkTUgrdTQKfOCKgsBUfyZ2OiSaJ7OTtpGblU0QSssJ
            TeTrbRGf8X1TiHs5i5//6G2/FlSONI8rv0aeBggD4Lhs0n3Vk3ruEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-13T19:41:02Z"
    mac: ENC[AES256_GCM,data:lheyS+GA6OUcqjyA5hRzMBgalFxm0Aam+Wz9zDNXsuV76RmJJIuXWh0CvSosVTdPn65I4w5o9dezf57UBe2A0FcwClLT8lDuvAvPeYWXNnsdyohStaWK8jIpr2J49O6rvtrryoSTH5HaIEhu0e/T3SsFsib/ZjxtiCKw7fbSO7M=,iv:kk1N7Q8R6VkSDfknPciP/aRJB7xHMNvfjl1bjvvquXE=,tag:fsYal6r3Jk/tsOlHswTH+A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
