users:
    rdeville:
        password: ENC[AES256_GCM,data:mNu8O2pjJwuFZrJpbj52fQceM4lnmwo1DNKsD00NknKetkAdUSfT3Bjhas4lbhIh3TiYwLcjaxsuOKtdB53oHMElL5jKyLXX5g==,iv:iQ/sqrlsOusPMoFlOf0zde6gQVezaWPDmVJozcWoTRE=,tag:Rso3LdHE8vx3VJRROK9svA==,type:str]
    root:
        password: ENC[AES256_GCM,data:BXGrzJv4odBoxJPQHik9RwEFUDVRNMkYb4zyblRQeIuBoVAwHA/zX/tXmGb3QWzyWUaGPmvWzhjX2B+q4bzNEDlakwE50Sc3cA==,iv:qnLIAEi4GK+62N6ZmLs+Pb+67HK468+3EWVNiigIGGU=,tag:AsN3f8d9DX+Le7a+63aUyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5w53ch2ym5qmhew239j7qh0q0ax72daq42qvvwexferta2yrprsf4kes9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSEJxcVlnV2xVSTFqaS9Y
            dkNJbWtZMFV4OC90TTZsWUNnZ2d5WVhqcmlFCnJNZ1pGV0czS2Q5eFQ5eXpudSth
            cUd5cThBdS91bGhwampIWitVRTBaR3cKLS0tIGxlSGlHK013eG9MdllKcUpKYk8x
            dzAxeCsra0liNmhwcDdKM2ZOVzdmTzQKqjof//neS0caK10FtzC9bbTpgi2ceWjV
            ioaj3IL5dZOw3NBEv7MfJYclqUq/dTOla8UbUkI/QQuG5TavfWegxQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xvyjy75jzuyvsaw5wxsexsjnnq24m50kdhezu8etn3x5j32cxq7sjr4aes
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZXZCd3lEVkUzQlBIT2oy
            Q2xua0R5Z25EQWdwL0ZqZ0pWYTZqN3dIdHpzClhRUTV2OFJ4SmJsQ1FYOUlzRUtD
            WlRuOCs4TWg0VEliNlBmWm9UR1M1clUKLS0tIEVVMEhwejZxL3F6b0RoRDNibzlK
            RTR1RllzWElLZ0R0b1VQM0dPTkJpSkkKwfzB7ahIxYMZQKD2uZ1+7+P2PwTGmGv7
            YChwVQz2FgXxoPywJmnVewFDaVUE/c1BCROmLbhbYc/eFM3sWUgh4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-14T00:30:54Z"
    mac: ENC[AES256_GCM,data:zM1iddm88a/JbbZ+65MU8aOwDHjSzqulXxh/ky3pW9IN6s8iNpeAqqtV/DL/lsOdY9NkI/ejoRynVubf+Lx9U97Z7d3RHU3BsrMWYc3hqsZylw0722tb1eDh8eDBOQtGRQSKaef3QADbNchtqaJ/Y4uFp2StB9VBr1/TYiLM7eg=,iv:dFGKz1Re0xXgTIQDRyw0s9vALLFqY6/I4I+AKWL6Yu0=,tag:EeDHSeIJSjbPyUuIy9MdLA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
