users:
    rdeville:
        password: ENC[AES256_GCM,data:f7JFdF/OW7bU5WzJogu1srkf+YvkAoHOK+E6pbyBIIgAUI8jUizkdnm0Bt90FkEGxPFec74+ca29vXfNEtfUF36Dd9apJdbXlg==,iv:ezxviNJYHa5Rs9KCkgZldXul6YI9vXmeDdAgxQRrT1g=,tag:297Vw5t+fJFgL0Z7L3ETKw==,type:str]
    root:
        password: ENC[AES256_GCM,data:uSBS0+EOzVctK4TY7WJFBNei60Mg/aiYZ6mtRpgNiuyOeHrcwkM/hkUXTF2T/AtdbQF0wu5BN7uV2rpjwd6IIP8Kf7AB9KjwMQ==,iv:s8AYsmkoVXVLIQ8zEKU1u6EImAIlFr21K9XQxIEvyKw=,tag:I7fzT2N/3OjhJ3GQyTke1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5w53ch2ym5qmhew239j7qh0q0ax72daq42qvvwexferta2yrprsf4kes9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdjdwWmpYc3p5blR0YUhj
            aldnaXU2YklYN0VuTnAwRHN3RDJrRFpyODJNCnhhem9UNFk3RU4yS0F2TnhxSndS
            S3lNWVRJaU9YWXJESjA5end2Qm9uejQKLS0tIFlWQUFTTGNJdHJrQmVUUlcvcU1D
            Z083SU1lTzVJY3B6TVNwZkRhS29SbkkKX6/zOKhpLytcrhaTfT+XiI6CxpbrqxIk
            vIVpiTEMvCyXbhXtIzULuxoef5ZG8j+73PHvEiU3eV0svmjXsivVLQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zx33d4eexmx0ca3yck4ykpz9624e0r5plxlzdedysetj3tg44awsxmnj8y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVStHUnU2Wld4WEI3R2RG
            WkhBNUZUS2h6WjNzaFhDMUR4R0RTNXlFU1hVCkFFVEIyZk1DWmFna0JCdFpMaVY4
            S1QwczJXM1JOa3grVmtKZDhXNld3Q0kKLS0tIEh0dzNaNDJjVlpETWJRa0tXTHpq
            eE5HSG5mQlFyeTFPVExodlc0Z25MQUkKq6rJgXASQBpdb4llu71/Ir1SsCjMOamZ
            0Qk22qFQpH1dTv/k2KX09U70S9jwokeoVQLmGCUF6LPmv13ka4CW4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-14T22:50:13Z"
    mac: ENC[AES256_GCM,data:2CL3nxZRewgGDmawkb4CJDzYMh0trGQAuLEduROmgZDrONM2QakD0pxjxosLXUhEFkJN14qb+o9JWWMpULQmQFnIGlKiWvGR2O9zx1FtCcuz3UUsfGS+AoX3b7fRsnifWLifYkWAxtPB3AsJHB23jjGHLpkpaVeWk8GLUfhP5TU=,iv:wItyU/21n85N6tHxzEcwqB5FgrMsYFrFni4xFEND+AM=,tag:Iyo5vvQdCRwnivjVxPdQHg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
