keys:
    # Personnal Superuser
  - &rdeville age1z5w53ch2ym5qmhew239j7qh0q0ax72daq42qvvwexferta2yrprsf4kes9
    # Darth-maul
  - &os-darth-maul age1f5er6rxrgppzw6wes94qjxun2v22xkjzkczhyd86879dxae9qvfsmp9xjl
  - &hm-rdeville-darth-maul age17um38qhvjkseq3vly7hfuetut5af2nc9va8l2004vgyfkn3sdy8sszkqv0
  - &hm-root-darth-maul age1spywc96sgud6r2c0ew668u5d2c2wp006p0awvxlzagkuy7kzddpq5uk22s
    # Darth-plagueis
  - &os-darth-plagueis age1wcc9qfkk3alxjuf3p5u5yfguxrdqltu2gss96tx90wmg2te9vykqdqasm3
  - &hm-rdeville-darth-plagueis age1fv9wshc62xc8qcxcavt0550uwakggsur0qp737nyyy0wyqlqw59s9fmlgw
  - &hm-root-darth-plagueis age1sxgexrse6zhtneey6s70rvuwy5zm6yltuasm7gjupstsr5s73vvqs858z2
    # Dev
  - &os-dev age1hk5a9lka69hm50gmafzjfd9rkyarmu2m64v0e6t9vspn2ttfu4aqdmatc7
  - &hm-nixos-dev age15vdy2vlpfn9dr4uhaygyfr5ng7geqqmv38aa98l67mhzw2k69v9qq9rglz
  - &hm-root-dev age13c5qr96srpn27m8ct5g2jymgnfa6ks5xyc8mypqmsfd9m37u7cls3dlhaw
    # FBLP-181
  - &os-FBLP-181 age1fuuuq5x54ermwumqyz2elwd3aqtvgqyhedzxu2p39zz2va32fc3sul45y0
  - &hm-romaindeville-FBLP-181 age1uxgqmys32n6h5xm8stqp8hfj349slq9cy3dl9slj3aa6tpu5ssqsqu32ps
    # Palpatine
  - &os-palpatine age1f8c90sspf24st3t455m079nssvy9tcdumm57ane9cydzk3dgyf0qefss42
  - &hm-romaindeville-palpatine age13lhtkcjfq3ahsjp26zcgwvtvns64z3kt6fkutkl8pleff2zu9dysztvfc0
    # Rey
  - &os-rey age1zx33d4eexmx0ca3yck4ykpz9624e0r5plxlzdedysetj3tg44awsxmnj8y
  - &hm-rdeville-rey age1sg8swpg9vugyh4fuqlm2dmp9macsges4ehu3swn6evmudjpkaq8q239r53
  - &hm-root-rey age1n8j86v72u9wdfvx7umr329grw3p6sa82aezg9v9eufw9teztepas4u3w6p
    # Usb-amd64
  - &os-usb-amd64 age1ft2ryp6lzr24va7xqru7tl5nf7nlk22rg66gnjfhgrkcfetltpkssmksa3
  - &hm-nixos-usb-amd64 age154mt92kyefv466c8kwvy06nf4ngxm4twcrrpz2md7jxeu2m6vfqqzd3q2f
  - &hm-root-usb-amd64 age1ju3hh8ywt4sxyqdce8c45gxl7cdyq67h5q4e0a5082nx768pcunqrmwhzt
creation_rules:
  - path_regex: darth-maul/rdeville/.*\.enc\.(yaml|json|asc|txt)$
    # Darth-maul
    key_groups:
      - age:
        - *rdeville
        - *hm-rdeville-darth-maul
  - path_regex: darth-maul/root/.*\.enc\.(yaml|json|asc|txt)$
    # Darth-maul
    key_groups:
      - age:
        - *rdeville
        - *hm-root-darth-maul
  - path_regex: darth-maul/.*\.enc\.(yaml|json|asc|txt)$
    key_groups:
      - age:
        - *rdeville
        - *os-darth-maul
  - path_regex: darth-plagueis/rdeville/.*\.enc\.(yaml|json|asc|txt)$
    # Darth-plagueis
    key_groups:
      - age:
        - *rdeville
        - *hm-rdeville-darth-plagueis
  - path_regex: darth-plagueis/root/.*\.enc\.(yaml|json|asc|txt)$
    # Darth-plagueis
    key_groups:
      - age:
        - *rdeville
        - *hm-root-darth-plagueis
  - path_regex: darth-plagueis/.*\.enc\.(yaml|json|asc|txt)$
    key_groups:
      - age:
        - *rdeville
        - *os-darth-plagueis
  - path_regex: dev/nixos/.*\.enc\.(yaml|json|asc|txt)$
    # Dev
    key_groups:
      - age:
        - *rdeville
        - *hm-nixos-dev
  - path_regex: dev/root/.*\.enc\.(yaml|json|asc|txt)$
    # Dev
    key_groups:
      - age:
        - *rdeville
        - *hm-root-dev
  - path_regex: dev/.*\.enc\.(yaml|json|asc|txt)$
    key_groups:
      - age:
        - *rdeville
        - *os-dev
  - path_regex: FBLP-181/romaindeville/.*\.enc\.(yaml|json|asc|txt)$
    # FBLP-181
    key_groups:
      - age:
        - *rdeville
        - *hm-romaindeville-FBLP-181
  - path_regex: FBLP-181/.*\.enc\.(yaml|json|asc|txt)$
    key_groups:
      - age:
        - *rdeville
        - *os-FBLP-181
  - path_regex: palpatine/romaindeville/.*\.enc\.(yaml|json|asc|txt)$
    # Palpatine
    key_groups:
      - age:
        - *rdeville
        - *hm-romaindeville-palpatine
  - path_regex: palpatine/.*\.enc\.(yaml|json|asc|txt)$
    key_groups:
      - age:
        - *rdeville
        - *os-palpatine
  - path_regex: rey/rdeville/.*\.enc\.(yaml|json|asc|txt)$
    # Rey
    key_groups:
      - age:
        - *rdeville
        - *hm-rdeville-rey
  - path_regex: rey/root/.*\.enc\.(yaml|json|asc|txt)$
    # Rey
    key_groups:
      - age:
        - *rdeville
        - *hm-root-rey
  - path_regex: rey/.*\.enc\.(yaml|json|asc|txt)$
    key_groups:
      - age:
        - *rdeville
        - *os-rey
  - path_regex: usb-amd64/nixos/.*\.enc\.(yaml|json|asc|txt)$
    # Usb-amd64
    key_groups:
      - age:
        - *rdeville
        - *hm-nixos-usb-amd64
  - path_regex: usb-amd64/root/.*\.enc\.(yaml|json|asc|txt)$
    # Usb-amd64
    key_groups:
      - age:
        - *rdeville
        - *hm-root-usb-amd64
  - path_regex: usb-amd64/.*\.enc\.(yaml|json|asc|txt)$
    key_groups:
      - age:
        - *rdeville
        - *os-usb-amd64
  - path_regex: contact@romaindeville.fr/.*\.enc\.(yaml|json|asc|txt)$
    # Contact@romaindeville.fr
    key_groups:
      - age:
        - *rdeville
        - *hm-rdeville-rey
        - *hm-rdeville-darth-maul
  - path_regex: contact@romaindeville.ovh/.*\.enc\.(yaml|json|asc|txt)$
    # Contact@romaindeville.ovh
    key_groups:
      - age:
        - *rdeville
        - *hm-rdeville-rey
        - *hm-rdeville-darth-maul
  - path_regex: common_secrets/spotify.enc.yaml$
    key_groups:
      - age:
        - *rdeville
        - *hm-rdeville-rey
        - *hm-romaindeville-palpatine
        - *hm-rdeville-darth-maul
        - *hm-romaindeville-FBLP-181
  - path_regex: .*\.enc\.(yaml|json|asc|txt)$
    # Default encryption rules
    key_groups:
      - age:
        - *rdeville
