keys:
    # Personal Superuser
  - &rdeville age1z5w53ch2ym5qmhew239j7qh0q0ax72daq42qvvwexferta2yrprsf4kes9
    # Darth-maul
  - &os-darth-maul age1hylp3390lkmpfjw4t0e606wsmxsxsnfrx7w0z5qg9enzlqrhj9dqckqas7
  - &hm-rdeville-darth-maul age1vs609j7uujwqhvssefpzz9jk2m5m7kr3k8dy98wd67npaf5zkf3qdm6v6n
    # Kenobi
  - &os-kenobi age10wdnn33e698902prd9q57f2adg9vd3ttwcv9sgeq0kc2seh5jfjssn3uvj
  - &hm-rdeville-kenobi age1q9sr0lpusj2v9npkhn67uy2ylhfz8xqj8qsczuruezqytjxjwq0sazjz8l
    # Leia
  - &os-leia age1ajff0yw9cnyve0zkqm73s7rswhjuefxzm8ry6c63syjx3yv4l9nqveklt9
    # Luke
  - &os-luke age1lh4jzqvx7235f047kfclw464fhrztn3v9rzm56ucz33t36xelf4qvaxu7j
  - &hm-rdeville-palpatine age1zpspypff2htcp7990d6ejn84h48cg5m70s6vujjmz8xruzrsufxq0ex0sv
    # Rey
  - &os-rey age197rrulzasp37ew22yhwd5h4rqxtka2pxcl3t4056zl8rgnwa4q7q92266d
  - &hm-rdeville-rey age13vptv2mspy6dy5c5kvduqfencmlcjvgtqsvul9cnehncrvuym3lsxe3hen
creation_rules:
  - path_regex: age\.enc\.txt
  # AGE key files can only be decrypted by @rdeville
    key_groups:
      - age:
        - *rdeville
  - path_regex: darth-maul/.*\.enc\.(yaml|json|asc|txt)$
    key_groups:
      - age:
        - *rdeville
        - *os-darth-maul
  - path_regex: kenobi/.*\.enc\.(yaml|json|asc|txt)$
    key_groups:
      - age:
        - *rdeville
        - *os-kenobi
  - path_regex: leia/.*\.enc\.(yaml|json|asc|txt)$
    key_groups:
      - age:
        - *rdeville
        - *os-leia
  - path_regex: luke/.*\.enc\.(yaml|json|asc|txt)$
    key_groups:
      - age:
        - *rdeville
        - *os-luke
  - path_regex: rey/.*\.enc\.(yaml|json|asc|txt)$
    key_groups:
      - age:
        - *rdeville
        - *os-rey
  - path_regex: contact@romaindeville.fr/.*\.enc\.(yaml|json|asc|txt)$
    # Contact@romaindeville.fr
    key_groups:
      - age:
        - *rdeville
        - *hm-rdeville-rey
        - *hm-rdeville-palpatine
        - *hm-rdeville-darth-maul
  - path_regex: contact@romaindeville.ovh/.*\.enc\.(yaml|json|asc|txt)$
    # Contact@romaindeville.ovh
    key_groups:
      - age:
        - *rdeville
        - *hm-rdeville-rey
        - *hm-rdeville-darth-maul
  - path_regex: romain.deville@dougs.fr/.*\.enc\.(yaml|json|asc|txt)$
    # Romain.deville@dougs.fr
    key_groups:
      - age:
        - *rdeville
        - *hm-rdeville-palpatine
  - path_regex: common_secrets/k3s-prod.enc.yaml$
    key_groups:
      - age:
        - *rdeville
  - path_regex: common_secrets/k3s-stg.enc.yaml$
    key_groups:
      - age:
        - *rdeville
        - *os-luke
        - *os-leia
  - path_regex: common_secrets/k3s-stg.enc.yaml.bak$
    key_groups:
      - age:
        - *rdeville
  - path_regex: common_secrets/spotify.enc.yaml$
    key_groups:
      - age:
        - *rdeville
        - *hm-rdeville-rey
        - *hm-rdeville-palpatine
        - *hm-rdeville-darth-maul
        - *hm-rdeville-kenobi
  - path_regex: common_secrets/spotify.enc.yaml.bak$
    key_groups:
      - age:
        - *rdeville
  - path_regex: .*\.enc\.(yaml|json|asc|txt)$
    # Default encryption rules
    key_groups:
      - age:
        - *rdeville
