# Replace capslock with escape
setxkbmap -option caps:escape

# Start window manager
date=$(date +%Y-%m-%d-%H-%M)
awesome \
	>>"${HOME}/.cache/awesome/stdout.${date}.log" \
	2>>"${HOME}/.cache/awesome/stderr.${date}.log"

# vim: ft=bash
