...@"../_classes/interfaces"
...@"../_classes/networks"
...@"../vars"

kenobi: |md
  # Kenobi
  | {
  shape: rectangle
  style: {
    stroke: blue
    fill: white
    font-size: 48
  }
  ...@interfaces/main
}
...@networks/main

kenobi.enp1s0 -> wan
kenobi.enp2s0 -> eth-public
kenobi.wlp170s0 -> wl-public
kenobi.k8s-prd -> k8s-prd
kenobi.k8s-stg -> k8s-stg
kenobi.wg-kenobi-pri -> wg-private
kenobi.wg-kenobi-pub -> wg-public

wan -> internet
kenobi.tun-illyse -> internet
