...@"../vars"
...@"../_classes/networks"
...@"networks/main.d2"

classes:{
  net-label: {
    style: {
      font-size: 36
    }
  }
  internet: {
    style: {
      stroke: green
    }
  }
  eth-public: {
    style: {
      stroke: blue
    }
  }
  wl-public: {
    style: {
      stroke: blue
    }
  }
  k8s-stg: {
    style: {
      stroke: cyan
    }
  }
  k8s-prd: {
    style: {
      stroke: cyan
    }
  }
  wg-public: {
    style: {
      stroke: red
    }
  }
  wg-private: {
    style: {
      stroke: red
    }
  }
}

*.text: {
  shape: text
}

wan -> tun-illyse {
  class: [internet]
}
wan <- tun-illyse: established {
  class: [internet; net-label]
}

eth-public -> tun-illyse {
  class: [eth-public]
}
eth-public <- tun-illyse: established {
  class: [eth-public; net-label]
}

wl-public -> tun-illyse{
  class: [wl-public]
}
wl-public <- tun-illyse: established{
  class: [wl-public; net-label]
}

k8s-stg <-> tun-illyse{
  class: [k8s-stg]
}

k8s-prd <-> tun-illyse{
  class: [k8s-prd]
}

wg-private -> wg-private{
  class: [wg-private]
}

wg-private <- wg-private: established{
  class: [wg-private; net-label]
}

wg-public -> tun-illyse{
  class: [wg-public]
}
wg-public <- tun-illyse: established{
  class: [wg-public; net-label]
}

wan -> internet{
  class: [internet]
}
tun-illyse -> internet{
  class: [internet]
}
