accounts:
    contact@romaindeville.fr: ENC[AES256_GCM,data:6khtnMjYcbNpjeTKpcMUV6crwPH0xZiF9w6o0w==,iv:4ZdSy0tboJ/CBVzlVCCDRIB85XqVGKLTsvwCKtpmx0E=,tag:8fiRPFNZR58ysnqkrmlQeg==,type:str]
    contact@romaindeville.ovh: ENC[AES256_GCM,data:2qkKHU0gIozWUipXYevflj0F2yIQSbOAtYIUc2YjBg==,iv:niYCQVgZ9h1qX1TX/L3/Ap/3+gHVzYHKbCWcbT3re2c=,tag:9b02ViogEwUvCPc2RPRVRA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5w53ch2ym5qmhew239j7qh0q0ax72daq42qvvwexferta2yrprsf4kes9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbFRoci83VkQ5ZkVvK2t3
            anNPdCtpSnVPMExuYWV1cnpwRmVlT2FJK1RnCm1pbmw1U2k1L3FFVzdaTUJ6dm9o
            TklTdTZRcnNBM2pSbzNGTEpEbjFZUGcKLS0tIER0OCtobVZKdGZ0YXlTU1pjM0ZS
            amJBSU9YaTVpRy94ZkRsOGNUUk9JU1kKTrDD0bbt8N/8UAYMAiuSGTKEO2unPrlx
            lQ9wZSyYjvMTIGpYWrD9bCn5yI7x5pR0m11b3kbuRz/IjasDVPxaxQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x74gl6dq9mlj7hka0qe4cykhf749wjzax5cc97leumvvhllu09cs6h44n5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRHY3eVpVMGJIaCtHeExn
            MHg0clpva3V0aE1xRVZkRmFLcXpka3lueGpJCmtGY0FqRVlza3I0WW5TMEM4R052
            WklHUDk5Vy9HbzFUT1p5SlBNSXlTYVkKLS0tIDRsKzFFMzZSRU96dzFNT21vYjNG
            aFpyTzhiSkxCSmlKRitlL2l0YkIwdDQK12fKE0ULveSSoSP3fERDm3MvEJOZJNMt
            hCU1q1vF+0NLkgR36ZfuE9tDCcCnhYYKFi1tD6eOjuubSGcLQ9V5CQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-23T20:39:56Z"
    mac: ENC[AES256_GCM,data:i4ndzZXTQxkATXxhqeZQZVKfNfKVvUFF3M2060nf17tvbjLKdi8jDs4xP9MkI4fSnbGJENoG7FndsB8LbOg1RcV1Rfe1hYA/1ardHvzE73mEgxCP07ThzytRK+SGRC84sSw2hkkkDvINkP90epCfmNaLuq3ki1tf9JKALJjhMls=,iv:HCXahEqDinemjxmhoNTyQi+4QKPot+U37bZlSpbgt8w=,tag:tIY+qQQd7O1z+h406zaGZQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
