accounts:
    contact@romaindeville.fr: ENC[AES256_GCM,data:FLw9cTDEwodxXGoQ+ESyV/1iqjpypZDwDHpmxg==,iv:jYFJmzB5vGDrYqTc8p5ZenpB+ETDH87x3s9hqn3fMl0=,tag:U72jFULFtndqU8ZJ1FkyzQ==,type:str]
    contact@romaindeville.ovh: ENC[AES256_GCM,data:o23jlit/y5gbzq1UEahooN2rYukVBlINtPbYgzdqSg==,iv:92FZoqjQMrJ1HSaKx1aRdpIjsZHQmXYN4BnWumaoboI=,tag:ahvOOtRsq32YpNBWoC854Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5w53ch2ym5qmhew239j7qh0q0ax72daq42qvvwexferta2yrprsf4kes9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeHpoYUFEZXRmSmZzUVgv
            Yk5VdFgwREl1ODZXMGNkMzFqc3FKbjdIZTMwCng2NUxWTmJ2SDVzQ21LUmxpb25x
            S0RVUWk2Vkg1aDNJU1JLcXByWWt3RE0KLS0tIC9oRWlJbmRLZlk0dDlJVTJQanl3
            VFB1V1orZUdBcHVwK0VZcXlMZVpMS1UKVYAEAjvzseaxKSTHHXzVYEXak/L4kTTn
            96zeDGwPUMMEAyVhVeViyyIdqDJlIfleAcUXD9o/LjHlfPz6nmSHiQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x74gl6dq9mlj7hka0qe4cykhf749wjzax5cc97leumvvhllu09cs6h44n5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQjlIQWpZK09mR1pEZ3Fx
            WUhpWkJSQ3NxRG1WT3IwN2dWSlo3S3NYOWtrCnBxOEdYOGZxWjVmUjZQTURCcWN5
            ZHp3R043Unp1VXFuam5wOHVleFBOZVkKLS0tIGM5RnRHUGVHVWtVTkNCQWMvNHg1
            cHl1SklWNTBaZEVMYW1Xd2dLbjJTL2sKQlS2gZM8yw8rJajUhaIDa3YM5VsyGbxu
            wQ7f4I7gfTa4FXjvlDBlmVMw6dlnPu5UvwbvXZMBsNz24pRJt6c4+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T20:38:45Z"
    mac: ENC[AES256_GCM,data:CUAnx3FRLvOK5xv2VyooZEcGaedouy+l9E0X+wXbFBujUa4Wu4ltNmaM3d16LbD4sdHmiNsx650YV61OE0KkGKeQx/c2dTPsdqYU6RGkpDq6irwFfYTvF2LBnnGaW6CBJZOn8flb7YzgkldV6/7XOwY8Fzw1ASFybaI9mZ6aVz4=,iv:ULFwMMr/kHiJOMEZvlzA8x8n6bNI+9l5FIuwRJI3g+0=,tag:colXJd7kiiPmQnDuKxYoHA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
