accounts:
    contact@romaindeville.ovh: ENC[AES256_GCM,data:DUapNqWuAxBEGaBo0zSqIaxvZNjAj9RYSgsp0xiKow==,iv:P4VjGmR5DHdZNc90cAl9zl8PrTXhPL3IkXuyAh9RwUM=,tag:dRvWFoCGqgstArgmYwe5CA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5w53ch2ym5qmhew239j7qh0q0ax72daq42qvvwexferta2yrprsf4kes9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsOVpYanZZc2ZvazdBanBv
            NCsvcU5HSHJ5VHhGRW1RT3FSaVlGdWlzbzJNCkRqVjV1bmZhVFFkUkRyUUNUNFla
            TE1yMm04bG5nV015bXc3eWpiWStiQ2cKLS0tIHlZcWsvYTl5bGtSUXVMbytaQVB4
            bk9ERXBqdjY1cHZaR3phNjRVL0FIa0kKnLAk9zM3WA7ZEcuRJFGOokFEMuxKxE2i
            ytaaavi2Ol63jIwRLSFE6gs81o95gREskVTmx5toE7Yf108215BpWA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x74gl6dq9mlj7hka0qe4cykhf749wjzax5cc97leumvvhllu09cs6h44n5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUUJxRy8yUE4zM0twR2JQ
            OWhtS0xvblBLYWZnYTZWcnNtUHEwUDhTZlF3CllXSStsclRlM1FHdnFLanlkakg3
            dVFWS3NpV2p6M3BvbXUwRlFhT3VrZmcKLS0tIFErK29lb1M3bXhMMVV1YTlsNnR2
            Y1BvL0d4TUY2WFhNOFFPc2NaN1RlU0EK2Vob0RSyyXGSAAfEiorBhaNnDNM+d956
            1duKHl/wh1hCSSoax6hRuh2Ru5ntrsxWHo1xe3YiiBAGRIfJO77gFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-06T09:10:55Z"
    mac: ENC[AES256_GCM,data:Y76hhutva7YA5cZKc4SR7zDXHCH8wISyXPZ1O1QVU0Za1bU8cdZy0VkejfQ9Si+r41XZcrEmjE08sADCkQ/aeuAtz2xi+mWlALSFBcEFOjIrIKeoAw/HjBA5u9xzCj0t85qLeo7/yW8r9ePTJtgXq7HkPkk2brTJUIjMJFVBgzc=,iv:xVtHL24FgM7HRf/SBE54KctOawn3rTRCCyxWl2lSv/s=,tag:IoEG4YytBJ0GTsXRG73h/w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
