accounts:
    contact@romaindeville.ovh: ENC[AES256_GCM,data:DUapNqWuAxBEGaBo0zSqIaxvZNjAj9RYSgsp0xiKow==,iv:P4VjGmR5DHdZNc90cAl9zl8PrTXhPL3IkXuyAh9RwUM=,tag:dRvWFoCGqgstArgmYwe5CA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5w53ch2ym5qmhew239j7qh0q0ax72daq42qvvwexferta2yrprsf4kes9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTEp4bUlrUTVrNXpvR05G
            Y3RsS2loQVFZRTNsM1UxdkNRS1dNQ09OejFZCnJhcUdlMno2b0kwNmk2dWVXZThF
            VSsrcHRoZjdraDVwWkpISFduWnJCRjQKLS0tIGJVaXZTcHpmVnZ3SVc0VFVDYjdO
            QWMxd2ZHWG5VYUVzNnRsVmx0TFJKN3MK1DkRoh0KGaAPOXi0c2yY/CiOFdkSUi3F
            klh/GhbadQDB7y5MbHzLcQ7JpZ6r5QvQ12FRNyBlmIT2QunBOQ/7BA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x74gl6dq9mlj7hka0qe4cykhf749wjzax5cc97leumvvhllu09cs6h44n5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGV2cvZWVXVzdSbnJ6VVJT
            aElCbFZBWkRWWWgvV0NxNXNjTmFKa3BoNm44CmJDeXFCRnBtdGh2c1FwRllMY2V0
            M2Q1c1RPUHREK2NjWHRUeFdndVk0MEEKLS0tIEFsVnFYdktaZnRmNzZqVDZZSnBD
            UDRLSlg4bksrQjdaS0dFd2RrM3BLTm8KaJkt6ASZg2yqOj76pkCgnbkqpIcg+k/9
            8wpyRPw2pmibbvFx23+dlY5OaiQcLOc8/8ZkW9IyrEoLq14StxTrrQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hyzjxh89pjdfpuu9dz5wkk8t2zq8renv0kwqjlxcnrm5zze9udtsyu2knl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZWE2OEFVbWVXY1RlMUl5
            OGUvNFZpd2FJQmxKQVFGZ09Jb3cycXpRL1hJCmVhWk1HV1psNEFxMlZFcTZ1eFh3
            SWlpTTB5aWxhTkNBVUt0UkNNTDVabFkKLS0tIHlob2l1MENhNm51eHN2NFNBaWhT
            cXp3T3VwSkVPQjIwOWFleGJ3ZmtVeW8KR9yV7e+VKaBC2ee6mWgAhVF7cteSg5AJ
            mjZ4ZMnwjPr0LbZTvlm8+UpRK3Rg6ONVtZ6Te2WCnNLpR3JddhMUNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-06T09:10:55Z"
    mac: ENC[AES256_GCM,data:Y76hhutva7YA5cZKc4SR7zDXHCH8wISyXPZ1O1QVU0Za1bU8cdZy0VkejfQ9Si+r41XZcrEmjE08sADCkQ/aeuAtz2xi+mWlALSFBcEFOjIrIKeoAw/HjBA5u9xzCj0t85qLeo7/yW8r9ePTJtgXq7HkPkk2brTJUIjMJFVBgzc=,iv:xVtHL24FgM7HRf/SBE54KctOawn3rTRCCyxWl2lSv/s=,tag:IoEG4YytBJ0GTsXRG73h/w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
