accounts:
    contact@romaindeville.ovh: ENC[AES256_GCM,data:nZqmpitrIWvsHcxCfqWSHnJMSVPb64m9mfxvKgvVlw==,iv:g5Bgh+y+vt4elEcHrCPDRS+yc99Ir34301XSzcqMSfs=,tag:eZKcwB3OTugEw39gnWklQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5w53ch2ym5qmhew239j7qh0q0ax72daq42qvvwexferta2yrprsf4kes9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTDIvMU1NNUY5WEphZmxl
            RmsxM1B6MzcyM3lUeEY2MXB3S3hTMVhGalRrCkpvVkRUZC8zZmZxK3IvdVQ3VXU0
            Q0VaeUdXQTNndm1weDZEN1BFaVVBNU0KLS0tIFRCbTZ3cE51N0NndU1mcVlpUk1C
            emg3aDFCSTU1dGhWTXdhdzZiVzVINWsK0+8aglg1IqVr1dLNkrDG3bAqi3aTVgcI
            8BpPzXDUNKdYWl91kt22QIW5LzPSJi9SBTo3oSz/h2E6E1she6vbRg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f6yc0z336wkj0ac0qhak2u2t5wqaksf8hpgxvn2mtas26hwk5gasx0th2l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdzZlMXdtamlscXBGaUZw
            b0hBeWQ2NnBsc0N3MFh1M2RUUGxkOU9ST0UwCmtIMVNvTEEvRFgyTzZTUWtPZ3Vs
            blNoQnlWK1dWVFZIMjllYTd0UWZUTWcKLS0tIFo4N3JFVUd3NGxWU2hndDRJWG5G
            R0Qrd1FwM2t2cGlQRlMvT1lvNzl0c0EKqEBeOHgikhlVI4+aI+lGsQHUXi5Rxtnl
            2N8Vb/TbdB6Xwt1g6jQ+d5lysaegLe7mgMTZxIOJXpUKH8P58GS1mw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17um38qhvjkseq3vly7hfuetut5af2nc9va8l2004vgyfkn3sdy8sszkqv0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsOFZDV0pEUW1rUnVNd2lK
            bVBFa29aSEM0anI1azNHaXdjTmpXb3VBRVVJCk1KMVFTU0JNbTJraE83MnpXdXFL
            Tm9xa2VCd1dnSnZFTWExRUF0cUtSV0EKLS0tIHVlMERnNzZENVE5YmoxSWh4WG4y
            NmdYcFFxRE42aUxKbThZR2xMWmwzbDQKQM67vmjEHMqbHtCxa5YuwsginShfV89i
            44uG6aNZdAz3ayFSlgGiSOt/BLP9sDOETObbHs3N54Q0Dp115T4H6Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x74gl6dq9mlj7hka0qe4cykhf749wjzax5cc97leumvvhllu09cs6h44n5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUVRtYXA0YTlvUllsQ2ZT
            cHRCZ3ZHWFBiTnZnN0lQY1lqN3JMYVM2N2pJCktYUW9qNG5RckZOa1ZSeWs3M2dL
            SFprK1FMZGlxNVdXckloMFVhMm0yOVkKLS0tIGhpcEhKSWNNS3Q4RlNQS2pFYm1s
            a0g0QWZmNFRxbVZ4NmRYeFVleURoN1UK2KtmLmYc2P6b42QZuQNPOb5twt5UtNxE
            Ot+jqhk0Cv0rTedjk2XzLpqfX7GojC1PejRaCg8KbkV67SjKoQ3BGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-13T00:20:05Z"
    mac: ENC[AES256_GCM,data:PEoXFLU597KW/Ugka8j78dvWSqlHOyY0WU+1Copb26OhSNtGRSOsNJMkxLiq5gEOc8P95fGc6fXIDV7YGgkpzecA73df4Yo1mq9rzryq7TQLbEzix15u+f9z+YCr6I8AY1WEv+cV/8Hx84gBqO7ZdZEUMMtR8naPG48U5o9NXT4=,iv:F1Wj3ck7TsXJWuxDOHwIGBeetO+cVa6d6ITcseS3az4=,tag:lq+tvay137QlPDb8N71eRQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
