users:
    test:
        password: ENC[AES256_GCM,data:BsKJJ7gHmTHW/aYT9wfkyZBMjFwRE8zHPkLN8WuY7iY7Zjndh4Oibpk6NXQ/yHmwARwpq3k+aRBqtCwCZ/wmV/nKDq5WscSJVQ==,iv:C8RfjXe7UmQOvG1/ZQUe4j/RR7a4l6xQOgyi2JwCxqQ=,tag:HaICtNJyuOezuBq2+bdOAg==,type:str]
    rdeville:
        password: ENC[AES256_GCM,data:AL/u8EfgUQSfCwjGZy2cj9lyueKoWypBCy4dTP9NCHyu6qG/20ps+pDSI7kUZ4AegoMsaeRMamuSissvWGdeO72AJoISGO+mIA==,iv:XTOyrVeMw8VkAV5IChiZhAwZJE8R7HPjbNHav8E2MDw=,tag:hkmU0Hgh/gtF246YCc+a1g==,type:str]
    root:
        password: ENC[AES256_GCM,data:KeLznlsC3PVKzhXyx2TkSxEgi5ajw/xk5O/oQJbAninQ+sJXdZDz5F9jGJCr3CgzhPFVGmO3tx4EZb54KmrX8jdog6M4yuZ2Dw==,iv:aNCW+gDdWyGk3/awSYjt2zQXIftvkqt81ScZkxYKmBs=,tag:27snRgUjGjivZHbWwaDkpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5w53ch2ym5qmhew239j7qh0q0ax72daq42qvvwexferta2yrprsf4kes9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUmdXSUZQQ0ltRWFnSEpU
            NjRpTSs3MXV3NWV5UGtoeHNsRndIU3MweEV3CmNaWFdEb3NZMVc5cG9iU3Z2R2Jn
            Vkg5TmlCZFd5VXFWQVRPRFU4eTN5T00KLS0tIFViRTJmR1J3SDF1dlVWVVhtVlMx
            cGtxMVZPenNMTUVtaWRxdE03T1d5R0UKvCGCfR3S0vbGFgUG+rglPnJg2e1NZvdK
            shTD4IflMgVoCayyqabRjDH6/BF3SNQq5PUK03Cvv7NCmHwuKrMTlw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1esh2u2a2vkehvs6327nv373mmvk2va8dn3rv2e8v33pe5aadzsdqnetvr9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNm9xbW1RZmJGWEp2U2dQ
            K1NLbTB5amVhblZyaXhhSGtJNjVxWmR5MlFrCm4vbGV1WEdxYkk4SDVIb1REZzdu
            UWdBcmhQcndueFRxUVNib0ZhN0R4S2cKLS0tIGE3aG9XUElFUzg1dHpUT1o5bys5
            TXZqK2pjWVhZM3VLc1J1OHQxVDJ2S0kKBvHr19dgGMWhVtcIHyPLYcMVmciyiEuG
            86+sh6vC1+J/gEjj829DTm5bRf8sWoSxqHdwbg7zEXp4YddAKhvvAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-05T19:53:54Z"
    mac: ENC[AES256_GCM,data:r6IB88XVzZpw3G/dX0A9M4+8/Z9KHo1LTrK5uq/0P52ZabP8wf/t6O5rt09g36iL6CnqyUvGqUzUQjIoPCQkl5i52rC9KBMJGOBE4tBu3TWiurmMKDh/zMDB8bYBfHD1atNb/F6VIqL6CU1mi/Xtisp+YipToyEMPSfu9ej6I10=,iv:06hv9lNWIrfX2LTMVsUB1zKEph5J23lBoMUSKZgxado=,tag:iZwCF9HB0Rz/EnyjbN7C/g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
