# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "ehci_pci"
        "ahci"
        "usb_storage"
        "usbhid"
        "sd_mod"
      ];
      kernelModules = ["dm-snapshot"];
    };
    kernelModules = ["kvm-intel"];
    extraModulePackages = [];
  };

  fileSystems = lib.mkDefault {
    "/" = {
      device = "/dev/disk/by-uuid/af13631d-9bb6-4fe1-baf0-ffdc3dbea0f3";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/00B9-BB0C";
      fsType = "vfat";
      options = ["fmask=0022" "dmask=0022"];
    };

    "/var/lib" = {
      device = "/dev/disk/by-uuid/d6c5cea2-a138-4036-8bcc-a21bb8cb2d23";
      fsType = "ext4";
    };

    "/var/log" = {
      device = "/dev/disk/by-uuid/c5d5b7e0-f28a-46ac-92af-805faf329eb1";
      fsType = "ext4";
    };

    "/nix" = {
      device = "/dev/disk/by-uuid/f7d08dab-6552-44de-9cff-ed28dff4fe8b";
      fsType = "ext4";
    };

    "/home" = {
      device = "/dev/disk/by-uuid/a14c2870-8025-4518-bb00-92b6b2e09958";
      fsType = "ext4";
    };
  };

  swapDevices = [];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
