users:
    rdeville:
        password: ENC[AES256_GCM,data:B+bWyZ/l/yCvRr4JSaFJDWRhDEbHATGl6b4CIPhbxxVGAZ270NmOXc5TS7CkVaPYH/XcQUfHqy7EgkCORQtky7rMnoF1nnao4Q==,iv:KawOQouYu6yQUE/mylPfR3NagJPPqiV75gmqDvTOTPs=,tag:+uN/h6J6eGooSJ/uXGXsbg==,type:str]
    root:
        password: ENC[AES256_GCM,data:/v1IDpOMiNiHQm0KsNO+48tp+O9rqFPOlZbUt+rARoCTQfU4YWTI850qgQHdFX5QGM+frRD3EILSHFtmlDeyyda/pNrDluIVfg==,iv:HI2kNVbjuEo6AFXtGJ8NWsc9A5uTgezIdVDvenbvYv4=,tag:35V9KRL858SjsKz6KmmfrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5w53ch2ym5qmhew239j7qh0q0ax72daq42qvvwexferta2yrprsf4kes9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArczJxVkVzdVZ1c3pxYStu
            OXNyb0pWVXc1ak5OTjRHanU3aVRORTdkTjBvClNodytrdmpwTFM3QTVtNGZPTEpM
            OHpFYlVadjFpTjZhWVhBR0Jib1RGWTgKLS0tIFRjbDk4NWpTUk5MTUpwbmZxMVg1
            TGhncnF4bkR4aWdnOVpicG9JZjdsTzQKyBF8daorNIB5aSD1QLPGede7bYWhOnrQ
            6naf9y6+F8Hc3WUOiEXA6rLhJmMKUJU0qhNiYtpYDVZQrrIpGxrJNQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f5er6rxrgppzw6wes94qjxun2v22xkjzkczhyd86879dxae9qvfsmp9xjl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ajlSNEdlTlhZaURneVhD
            ZnNIdlB1WS9pVWpLSHJma0pmYWV0Mi9zNUR3Ck5jN2hkS1g4VjhrK0wrTzNHU0R1
            STRwSXJZRFhKL3RCb2F1dnBwRDk3Z0UKLS0tIE9hWWwzMDFBdkZDR1pMUElKRHhp
            eUdmYUROajV4bklheE4ySW1NQmxjNU0Ko5IBBpVyHayaX7emS3UYX5lJeJd+ohtC
            JVvTut+/bJEn3jrBnj6npAOztQ0RNMbKJj87JHqwP0jZYNBG/TgBiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-22T01:05:40Z"
    mac: ENC[AES256_GCM,data:101aMeOWw6zbv+s4WbM10kdPZeWk8+YnzmnolVtjj3oF/sGkyCKMkFA8+64onjadWLrl62WSjLEoHMdct3neh6SQOLNsN6UXNHGpE4fOaFyK4rlwpZJuJdsMbsy6y+DKW8zxVhm+1jOVDVGHMNTaLtCQ46eNqVL936hziNIBi4U=,iv:Gcp09el6NJ1okr+nt4lbmyfQeONH3Q2zpbG8UTLIaCk=,tag:iZ+f1/kLth/4OGyoJFXMQA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.3
