users:
    rdeville:
        password: ENC[AES256_GCM,data:QPwO4PLR7HiSqjSJpEefs3kytzGP97/pemBJnXJIXgEQClr/sspCkhEj2SDiFDOVF736Sn3rAQOZzw7niM3UjvtAHZFYV02w0w==,iv:Hd1fuI9RJdOdRF71jBBSUc616R/DAeGzI+zqGux6PvM=,tag:rHMRvHxjIejJIc4vVJlSNg==,type:str]
    root:
        password: ENC[AES256_GCM,data:S0iN4XJ2cF54r4ma5QtyvX5kKxXAjepInOCFuoGsKgtJ1owmtXA+SmH58wTxlCAG3PcdVgqTp5O0qu+l5noz3dlRgt4FSA8VyQ==,iv:ew70GQUg5eOz8Jz5pLyKogWdi+D+TCPvNcP09vcHxF0=,tag:8pjT9zPh2h6YYpT1L1kBkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5w53ch2ym5qmhew239j7qh0q0ax72daq42qvvwexferta2yrprsf4kes9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0YWpYVTgzRjJIRU4ra2s2
            dUlxS2NsOThKWFIycVFibTRxWWJRYnZXNUVzCmxYSTZMd2EzdUtzc25UcTF1QkF0
            dVpRcUZmTEsxckFKeXdHWlgwODFRL2MKLS0tIEd5bEJtYmNQV2N5V0dIUnUwclVm
            Q1lhb05KUXVlbTF0cS9yOUx2T3dHUFkKeBfsrNa63ZTvz2GOnj8J8uZwNbonpDEh
            p2HApHoQ0EuCAcgPvz+FMjqdvNo+W86WxnApmAxsluOrMoNuBVOsUQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f6yc0z336wkj0ac0qhak2u2t5wqaksf8hpgxvn2mtas26hwk5gasx0th2l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Rng0WlV5eDR0Qk1zR0xu
            VHVPSSs0RHErZE13VmZtVTJMVmFaVkwyM21RCi9qanZlTTFoelIvNDVXcmNmNFIy
            dnhOcVF6bjNwNElxWUluY09DSENEdzAKLS0tIDhaNWNZeExkM0RVbzY3OXZ4MndJ
            MFBxZGZPOEU5Vnk2R2JsOW5nd3pENFUKc5ZtmoZmE5pSJU6t+ImKebeh4yL0Y/7q
            f/DLGtcHAR9yMKefBBMCDTCQYaICNBY2YwJBboD+8Ld8/nGa8zZuIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-14T00:30:53Z"
    mac: ENC[AES256_GCM,data:fB+LWhieaOZgHhoRwpny883v1trS6iBpsNF2sPAsBCXJdqSstsKBn87hwi3j2YpDPVJOx2f/AJqCyagobUtoC56UGQm5hPLSgi33NIiDtJk+nkI2cOaCbU5yDdC2cRkHU0vTDiHo9AwyXFXOiVeAnqTXx1bZOpzIa6Nm2H8B7To=,iv:1YEBxNAp1mU4a/euhYor1bfzD+kPZR9lbsxo1GSPHek=,tag:EebqcDloy8YLPLIP2YF1RQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
