users:
    rdeville:
        password: ENC[AES256_GCM,data:q5rI6ims9z+EcxgWtdBPX0kb6qRr1/kbxF2nzeLbMMzkbZFNfGKVihDDQ0jL7zTFV7PByek7b/PoBXAdY7hVyRJ3aQ23lEb4XQ==,iv:taNrXDM2uUaWmiV0fzued3JVA9EPsNhQnPMSkT9uuSs=,tag:O+lOkLg4ssLU7WU87eW07w==,type:str]
    root:
        password: ENC[AES256_GCM,data:1MEr88EdwE3PS0W0FUWoxaNsL/0SEpYszu6XfDdwUeujhvs+rgzWsWgvWDwkvS3zxPGF+oMgCKsqRLbQI60YpBb4XGClXxdGvg==,iv:J0wZeqYbjvWoaZKyz7uLE31LvbhmmuH8Wua+7LRXgXM=,tag:04k/Vt8sXGtSD7dZzuerew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5w53ch2ym5qmhew239j7qh0q0ax72daq42qvvwexferta2yrprsf4kes9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsa3Zrc1IwOHZBNTBGSEk3
            Vy83S1oxd1B6ZWkrYVF2RVhzMlk3ajc5Q0VnCnBkcllicnFsb0FnT1UyL2RQSzZP
            RWNFRzAvNy9WM0VPSC9iYldMdFMrOW8KLS0tIFQvY3psTVFNT3ZUUFRBQXlYdTlM
            OHQzWGF2WHV1d1RsWmlTeEJyTGhzdVkKs8keVitb+zMfhpMFnTNpujlOuBC2jCo1
            pZYAstuvtv/rj/lRHFyJMLATjp4YScpEj7YJl9QT+tbaTctwsqc3Jw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f5er6rxrgppzw6wes94qjxun2v22xkjzkczhyd86879dxae9qvfsmp9xjl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdkRKTnlKVFJIekFNZ1Fu
            cjhmQ3ZsUXVSallrVkRPdSs5dnVCM3JiYnhBCjl6SGRsaWRlR0lVTzJNRmx6Yjhi
            bXp5NHRvVkhVYkZEdlhjZDRkT281NkUKLS0tIEhkc2d5T3M0ZUlReTZ0cWxIWEc4
            ckxLZ21CazFVNnlka2tXTDgwZHRpVjAKulVFEt8f5iLwurZLvpLQjXgHhXObCVLN
            xORa1BKic1/maMYUOlJbbozLJoZDUOItqUk6FXEfQiHcKIY9O1AunQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-14T22:50:15Z"
    mac: ENC[AES256_GCM,data:IEn08OH/1+wRj99mU/5gtpLYELLF+jtL4Nz8v4TYYj07pAv3AMdV25GxhmAYJzWgh1uuOlXW2dW/523YfUZjCtgo5pbcEmdFrndeVN51Cu7PfQLILBz+wWR0MgFiUTM9Tg5bXmw2rPP/24jp1LKPYPLDfeXbyc6HRPdKB6gZy80=,iv:v33JUPhQeP8sMAsJxZ0T/qNBGGjmWvI+Fsoq9KsvmwI=,tag:5e10m8srBYjTMlVE/PIxhw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
