users:
    rdeville:
        password: ENC[AES256_GCM,data:TiciunXc+3fLfPVGGrlC8fED5l1aP0353v2IZmH9RYNHgItSFeKSqVvYT3yzpd8lfDbMojWL/yX8UJ2imztlNGq5/iZLyS7ejQ==,iv:zdCgWrblolfJXRIbOIrRqMZEsMakFoDmctRcdbbHbk4=,tag:RXqG2IhA4nM4y4Gc1vB2Zw==,type:str]
    root:
        password: ENC[AES256_GCM,data:uaGLzjSidOp2UnsAH1m6U7572rSTYa5CInSrS/gqqAL9uAIshK4qZudOOXPkR/ChGW90W9HlSfS09crpNZL5BHGCc+abl5IY5Q==,iv:fX5i/I3gWJStL30BkeqB++EV6pPNv6C47qQaMB+Vrzk=,tag:wE76she220uInGgJn2ghGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5w53ch2ym5qmhew239j7qh0q0ax72daq42qvvwexferta2yrprsf4kes9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUnhFVHVjRDliU3RrdkU0
            dmlDNGFaY090NVlocS9NQ2cvUk1Qb0hic0Y4Ck1JUStKZVYyOXEwLzRUOXZrSWVT
            VTZvTU1UajFCeUlsZXBCMGJVaUpuNEUKLS0tIHp0UjliZjNDMGxzV0pJMjAzM01i
            K0p2dkNFRDJDM1NJMlNWVmd6Z2tFTU0KbDkUbj+Usmyy83sQR/SOyKGFO7ZwMRCs
            I/Z/iXiMGoh7LcicbpRTAxm1dxNEoEch+YlNfxKaGXIBT1inzOPrlQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f6yc0z336wkj0ac0qhak2u2t5wqaksf8hpgxvn2mtas26hwk5gasx0th2l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaXEvWG15ak5TcWY0UUIr
            ZlBSVnlNUjhmdzcxWnVRczJSV1JRUUVSQUhvCmJsSmNQMlRNa09MdTJKTzNKZkJR
            M1plQmpaSFZnODFrY2YrakkrRWFJc0kKLS0tIHZjR2VPUlRTZGJEWEIvZnkzN2RD
            Tzd3b2xwM2J1WVdmSmxldFI2MCtxclEKDsT3bb950oU094mBr1i9sftk3v6w+CWL
            IPkNTK2SVyMhLiEXv4Cb1a8+1mB6g6P+zJbJWlbFFgjHxA+Q6EGsHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-12T22:33:01Z"
    mac: ENC[AES256_GCM,data:y7sqHS3kzaAr0vsPzyQzX8xRX8SGuxAaJQRheOxb3bPeBHdSZAPkqe5AoVHOfypzeNwD7MSofH+C7T7F+Mdz6vs0CfOMh96Nxmlmagg1wdKNSAn6ktt0Ln7gvauDXKGB+tlwvqi6IBy84GvOsDezpaFVx2nNAk+uHprz3ab8veQ=,iv:iQUS1rMO8KEZsqAS+2q4a5Svufe3F0l4Sl2xg8XjDog=,tag:8UwldjCmJBl6xa8jYxXmgA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
