users:
    rdeville:
        password: ENC[AES256_GCM,data:F0/i9nhQPaHs5Dw/A9urs0cSUcEdCNBRbk7/QckpDthb+MNOIocZFLGuh2QG4DqtYSut1cyGzdFtRCvrQvYqRleBG9xsxd1heA==,iv:fkDt8r+I7WLLR401y1zUkdxXxx7sUI9SmYaCeIdFrc8=,tag:iD3pLOwuTOK+ZTZFDgeX1A==,type:str]
    root:
        password: ENC[AES256_GCM,data:3L7eI6fe8Rzk93RlyREU6gxWl+OtkRcF4VzRCo/F/z+k1/Y2aFm7MNunzTu6P75zeI4CVhauHjDAAS2Q9kFjPSoZ+fcI18tERw==,iv:msBEBAbI+Y0pIESdjQoYODsCsr9uHIiy0cZHLuVgWeM=,tag:ZbNI2f0J+cqyq5cJDrpTqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5w53ch2ym5qmhew239j7qh0q0ax72daq42qvvwexferta2yrprsf4kes9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRlBmam9hMW1reXlTMFFh
            T0ZBcjI1Q2FEdjByQStsR0xYT0o5RE5FdUJzCkVUMHVuZGNKTGJ1aVpYNjcxY0xy
            dDlXQTJkRXVFWHNrRlJ4bUNNckUzTWsKLS0tIEYwTkFoRTE3RmliQUltUzE5dUlW
            MitBbXBLQWpDdENwNlpDUVYxcnphdWMKUUFcLFn8kSAXblvJNLE0og0tLs8ZOeAa
            0Am9YcjBd2TdhqXL1RVijA0wqIlNqwVWRrUa8cJkF0c5EplLeY/6xw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f6yc0z336wkj0ac0qhak2u2t5wqaksf8hpgxvn2mtas26hwk5gasx0th2l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RkM3cWJERkNsY09VYmhR
            dXZTRXJTQ2xiNk51cFRFQTJoVHdmM1crQW44CmNoUzBOM29vaEJxVHN5UE5BUW94
            V3QwbGdlUVJob1AvN3RRaExWUUo5TTgKLS0tIEZkU0Q1KzgxOVppOTZYMGx4SFgw
            djVuQUNteHN4TThESU1jY01iTWdhM0kKEUbGJNxIxQFaW//pwZAjP5AetHy/4tpK
            wi4xJNksEGUFRj+3y5/EsnoexPwcJp3hiH0piqwAZAAWLEGB/EcHag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-13T21:20:06Z"
    mac: ENC[AES256_GCM,data:JjG7uiYpToxTwkthAxJ+FIiCT0OLPO3AtlKM8L9w+/L9bHSjCk45Gg/MEh4BRju+y27imFhmnup8cGV1mpiby/5qa6wP39eKWq6kW5BOdcKiL/296coEuxBA9igFjS5Rd8WMq/Nsj7rP2CxhBjxEXyjzdBTzksAoM48v9/ICjL4=,iv://MS4thiFaBr2Sarv2ZolUxp4wTBr7NlpkE/jv1dr/I=,tag:2xu2prGzErDyVS0y8A8ryQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
