spotify-client-id: ENC[AES256_GCM,data:fFocw4zjcQAfQn1XLwEA9CKRg7Or+A3FvTlRghBmtOs=,iv:Ei61KOT7SJm0AULrxR1z0fpebr0cmXljLWwRnlu6/y8=,tag:jLjtxfB9yFqGRleEFhGtfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5w53ch2ym5qmhew239j7qh0q0ax72daq42qvvwexferta2yrprsf4kes9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcWljQnY0MzU0WE5tSWo1
            TUEzNEgxYURRenlQblQ5bFdGUjg1Qk5qTWw0CnZPeFZmTVlKRm5STkVFTjZ1U0Zo
            UUVJVWVnd2kwL1RNWkxhVmZuQjBlcEUKLS0tIDU5RlBnM1dxbVdISitqZk9DN3Q4
            WS9uNnprYld6WG5XYTU4Qk81elFzZFUKTL3KbW8uaSuKeISeUnF4ZgV4adBNRIW8
            5MaJsselCTGV0XHVPdK/p7Sn+bshdX7jbDKghy5LsDYnSid2RLiMpA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17um38qhvjkseq3vly7hfuetut5af2nc9va8l2004vgyfkn3sdy8sszkqv0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWDVJYW04dGwveWRiQkpK
            ZGovZUY4V29Qc2xUclJaK1E0aWhSVlozK0JrCnpLTFQ4WU5WcW45SVZlMC9zM0w5
            c3E2Rml1MDc2cHdJQlc0djFqQUlndncKLS0tIHArM0E2b0tWM25WTnpENEkvV0Qz
            UFFCRzBMbUdGUnlZUkt6d01iQzZqbk0KWDOCzzpI7r2dILdFJBs3BJT5iPkToHTZ
            oryCmpnnQv0LaccyHebDoGoMUT6CL20EFdS094IFdsxvNWkAk6BDPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-14T00:30:54Z"
    mac: ENC[AES256_GCM,data:uhMoz/EC/4PyNq7qliRQk+lf995IbqrUUm8+zrJPxMo+1KTAP0o+OlNGa4cinzPfqfLLFge3FEaGyaYGu0m8BdcABjFht8OwLpR84SobmK/S4DwCENQGEZvWxf8G77burCT0CNy1c5G4AJWgeax0l9uXz7cRAG5hz4/2XoAUt4A=,iv:0O5JE1CEFwXC6yOkQajAWrtCXCCojZfmVpwtGDGSJYI=,tag:WW3PtmD/AqxjcbYnp6YVig==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
