accounts:
    contact@romaindeville.fr: ENC[AES256_GCM,data:DLxslHlvnDREBPiDgl0ewEIdGqz1KzygXkhlOQ==,iv:cQimvJVSypIRb19ANnHV6+Evq+pv1tbGaRgI9405eCQ=,tag:NKD4XO5HSlaUVLErXz3uxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5w53ch2ym5qmhew239j7qh0q0ax72daq42qvvwexferta2yrprsf4kes9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWDNjNXRjZjdMTGV5NWVh
            S1hpN2NWem1UTExJcW5qNmsyR0JpTlRwQUIwCkVYME1ST1RXRFRkaE1XUzAyK0pQ
            VDB6QmtNZFZjT1BjYWJKUk5CSUtONUkKLS0tIHRIL1NNY0ZWeEdQdmY5THorYTZs
            Z0RkeDRZWTF3UGxDaEdsdVBTWTNHazAKFqh6noFKD54llSiallfa1Ko5mGsj4hlT
            nH1a8DPUpH1R2B1KvOhS/Vbdq9IFD66gE0Ywz3BTdh8CAuy5jJiN/A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x74gl6dq9mlj7hka0qe4cykhf749wjzax5cc97leumvvhllu09cs6h44n5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVS0JRZjJ1UmYzaTVQd00y
            T0cyQS9VTWdYRUZCSXh6cFJPTUNXUnE1cEE0CmZWSHk3YkZXN1lWeW5DWGcvS2Rt
            Y0pkS2VrU2xBNWhmbWxzSDRJTzdlbDAKLS0tIHRSVHNyQ0lrUVRneGJXTURVRWxy
            aFdEaXovd2ZobTF1MTlWVTFBLzVPS3MKPX+rZH4pgruvCMhL5rcEiTPtBfdWLkc/
            8LXQULgtYzQYjqnjP8wDFQwM3qV2g9lg/h8eRD26jYyOsAunSLTJoA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hyzjxh89pjdfpuu9dz5wkk8t2zq8renv0kwqjlxcnrm5zze9udtsyu2knl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVWJOUW1zZlZybmxlS3cz
            WmFFRlN5YVZ1dmxXUDFwa0MrZVcwMkVISkd3CmR3OGxvS2oxaXVLNmEvMHVKV1l3
            YU9kUDc4Y2IyM09xV1o0Tkd0YnZJbncKLS0tIHZEYkdwQW5zSS9ZeEg5Vm1peGdY
            MnNGTUR1OEhjQTV2em1FUzlnSnhMWFEKzI9pEJmWLTrMSqfQ70VvGBI/sbP0GzSM
            0Ewppp/5gUFymuCp9CCd6q12KkgGDT5fjx0uTbF22YyhNNZ+7dkzxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-06T09:09:32Z"
    mac: ENC[AES256_GCM,data:AnzGWjRVbI2Js4Kl8/4bwF1pWYAQCY4SdQinn9ads0SpA4StW1sB0QtNOsJEgYTk4+JcCUb19kKUv13OsGbaxfXVisPFWhEIv5AEQ0qcU8jmlDA2O4jc79Y/MsEyGYYc8UVVPSKORumfgKE124d3499up7D/Vg+qBP+wr6scTmU=,iv:OHdyMSopzwS6h6xsOMadPrSUSN7XSULPhYHPHrEvCMY=,tag:x6IwZVUpgDN6Thm18e9PnQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
