accounts:
    contact@romaindeville.fr: ENC[AES256_GCM,data:1uU4fMC4nRh3Zu+EG1oqwidra8rwJS2nPzNN7w==,iv:OkGGnbIPGjfSMpalTgeHpOM6bK5nIeezIDUVydmRvsg=,tag:wOqHBIftKNadN/hEuBQz1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5w53ch2ym5qmhew239j7qh0q0ax72daq42qvvwexferta2yrprsf4kes9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNDNHNk96RjdDS1FrVmpG
            dlR2RDFObmw2VjFFOFJkYVhha3dPeXBjdHdJCmtGelFPWjBLQ1gxclEzaUxIOTRJ
            RFBubGxmSGNkbDkwdlFQU1Z6bFNqQmsKLS0tIFYyRkpRcVlJS0lHN0o5Q1lFbmV6
            TCtObHpNbFZuVk5FcGN6NitCczluSWcKtvBLZyWFLbr1WOdhp3P2I5FX9wJkFZcX
            BAYyw2QAFxzYRc2tWOblS5UQI2bye4MQQeeD9hWOXsvTOboIX760bQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17um38qhvjkseq3vly7hfuetut5af2nc9va8l2004vgyfkn3sdy8sszkqv0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVDJONnRkQ09KQXpvQ2h5
            bDd3NDMyNDhPbTdXUHlYenZTNFJKSUduVW1nClYvUmNNWis5Y00vVGZIaURqanMv
            dmh6dVp2QUtmUUU3TnJvbnNoaGlDaWcKLS0tIHVhRExSTDVLR2tTK3dhYUVyVThp
            Q2J0S3BxUjQvaG5TUERkMmJ5OTgvdTAKw+7a0IFkqp0AbJv374uriQCl8GBbqKAM
            BZSK3CtDhgDdlvRh3rrn3YMDgg7e/A7b3lINXUiWNYAfL2n2TjnUpA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sg8swpg9vugyh4fuqlm2dmp9macsges4ehu3swn6evmudjpkaq8q239r53
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScWtqSWVLWXdhdVNLVE16
            N0pFNjNhUGlObTVFMlFVTURnakcrd09aeWw0ClZuRU9tZnBWbHZLajZKMVM0U3Q4
            NUdXZWdyQTROa2d5RWdtc3lMMU1wMmMKLS0tIHloTWJ0a0xSWGwzUHFrL3B6MXkx
            TDhTVk4wN3pSK1I1ZjFnR05VdE11bGsKfVt8JkvUkhIrIsXIbe4mMvWu7h+PB7DZ
            l0DMUO53ZM9rLI/fkVsZDiIBTEpeiik0ryLqvXPfU6yt+vZ0NkN3+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-14T22:50:16Z"
    mac: ENC[AES256_GCM,data:R+tK0M5dGjWNhoa5JnZj76Tb76d+59YZMlRo6M94iVNa6OA+8G3VGgV1vaWiX0crwjCurvy5mBZ9DACKHBkv5Y0XEDU+pG6TmhvPs2CXn74eU00MsWoJKtGO1s9PmWNQRkwgqbZ+T/llViAQaR8xRxGKIRj0IOZgATkYjI1GtvI=,iv:SRSdC+9ma1gufhx7bcLwblzonFhRZ0aGo7x4cYygtcs=,tag:OeLbNSXyfjA9ke2jDLqA+A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
