accounts:
    contact@romaindeville.fr: ENC[AES256_GCM,data:FREKXCH2Vm8GavpOugqMjuGYyTJRx8V/o4xybw==,iv:4mh5bltSBstpCvRSiUMcIX9anO5NFOX1JonOyUHDm+E=,tag:8q4KDyii8t8sz3HWzQcSjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5w53ch2ym5qmhew239j7qh0q0ax72daq42qvvwexferta2yrprsf4kes9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMnFrU29STW8wdDZueTV1
            U3lGT25odHl4QWFxaTJsWGQ0TzJaMmJ5VFcwCnBZZzFpTkxwNXpLblFZdGFobm1a
            V1FuSEhlMFRkbkozbzZseUxLeTl5RE0KLS0tIFVWa3QxV1JwQVhCVk40Q1FHY2xp
            MmNxNmVpNjFmcWVuQVlhM0R5emZoWnMKnU98DacMuIgu0PCia18MrAHeUgPFbD0d
            W9h5vA/lMHKCaOW2eSbXK0CDILymwglI5+RRGuJ6athhDq5qnhU57Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f6yc0z336wkj0ac0qhak2u2t5wqaksf8hpgxvn2mtas26hwk5gasx0th2l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0M0p3WVA3YW5WT0NKcldl
            TEdGTzhleFNVL2JwT1A2WDE1aTh0RmpPWkV3Cjc5eTY2RUJtRnBBYjlORkRwaHRi
            b3cwalMvZlpPMmVDQWJYS1I5ZDJoL1kKLS0tIEdwQTRzTndGaCtTRVJhR2VUZHUz
            WkJsdXI0UE0rV1o3eU1BR1h4SGZ4NGMKFfVCf5+LJnPshf9ZRJzDIivx25JBoGO6
            1H1ip2Y3rWjcjF4B+EdB/26SuVtad8fMP/uMgYL1Tj7rFJBCurHMpw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17um38qhvjkseq3vly7hfuetut5af2nc9va8l2004vgyfkn3sdy8sszkqv0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMFNwYkszTjRpc3RiVzN1
            REhxUTVlcXUwelpwOEhrcVQ1Vjhnd29kNkdVCi84c0ZINTlaVjA0TlVlN0Y4ZGoy
            SEJpdDRpQThuS1BseXRvaDJnQWU3ancKLS0tICtJZ1NOZmRPVjRTSUtZSFVBUnNP
            L3Y2M256UVdieEY5eTVZcTdWRnI0TmsK1PcPmK+kAgJ3wzLnjhyoWyxF0HaMsqjR
            8oz7W/fD8IAA2gd8CGGm0ud2PxoYVR+oDQF/MBdtnHJNUObwXCMlhg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x74gl6dq9mlj7hka0qe4cykhf749wjzax5cc97leumvvhllu09cs6h44n5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdGxlSTVIK09LLzU5WjJy
            STJicGFidEx1OC9sUnFrYVNLbndaZVhFTVJFCjBXcUgxWkxYelo3ekpxY0xubVBr
            ZGk1MFArZ2N5NzFNbTBBTEYxYTNQNkkKLS0tIFFUbE5tZHljRUZxZ0pNMmN2UWpO
            RS82ZzFXQXZwRGMvVlJ2alQ5MG9WbFUKAMV/4C8gyDljITpLby1JGD3ifEGYvQBx
            8QqdFlbq9UmFP7syckTSaff/bGucefldYZmN0G2bJj9uMVvJlUvl+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-13T00:19:15Z"
    mac: ENC[AES256_GCM,data:wmX95J3MFmij13n7MTglfjbMG9bV4BfJNhYN9w2lpz6bCd5N1XrPsC1uH6KpppGPTw3CQhKRleFBKHfMRTLmlmRl3YhCUvLTC2HuhCwL1GXnBmfvsrNkYcQQ0WKU1679P+qUgBjkE3Rp1GrXQ5uoq3BkstMOaA/27dgmv7dbyUU=,iv:wwSO/ymiwX5Ci6UAmtW+GPD+k9KZD4kZ+JxqFkJhWHg=,tag:uENgTnCOKYZXMsnSAeT/Yw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
