accounts:
    contact@romaindeville.fr: ENC[AES256_GCM,data:DLxslHlvnDREBPiDgl0ewEIdGqz1KzygXkhlOQ==,iv:cQimvJVSypIRb19ANnHV6+Evq+pv1tbGaRgI9405eCQ=,tag:NKD4XO5HSlaUVLErXz3uxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5w53ch2ym5qmhew239j7qh0q0ax72daq42qvvwexferta2yrprsf4kes9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2R1hVcFdIQlQ5a2R1eE9Z
            bldZNWIwRGdxbGZJMWVlUUJIUStWRHg3eFQwClVhSTd0UVhjQVgwTEY5NXBHRkRk
            Zmc4clIzTmRvaTdxakRJNUUvK3VzVlUKLS0tIHhoNlJJemxGWnNnY0lzWnRqSU5v
            bDg0OUNjQVlYbmI0YWF4M05xWHVVNDgKXB88hj7cywjx2D8qIZvgn0TGtBoWCBRg
            gHv0PNspBEl55XJclzAfwBRg68Udr2INK5jDLFkec+Rlbh2MqxYpNg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x74gl6dq9mlj7hka0qe4cykhf749wjzax5cc97leumvvhllu09cs6h44n5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPa2s0L0RoSzVEZlVkK1I2
            N21sRHRLWHB3N0RIVkhkeG56cFNUbTZ4RFJ3ClVoeDVGKzFxNTRIcm1XcDZuV3VM
            RnNEeDZReXB3VnVQWFNzRThXVU5VT3MKLS0tIGVvR3BqRXBUTkY0SlZpR0w3Wmpk
            UnpLaWZnQ2RTYXgrYXNOT2dRZFdMUkEK4Uf0CSLtabwPjMqXGBbMDSmThM7ca3U8
            rvFSUwg5LzbdgVcb8B/NkacvvRVDf2uw8KUdT3/tcYkO+iEEYEZ6BQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-06T09:09:32Z"
    mac: ENC[AES256_GCM,data:AnzGWjRVbI2Js4Kl8/4bwF1pWYAQCY4SdQinn9ads0SpA4StW1sB0QtNOsJEgYTk4+JcCUb19kKUv13OsGbaxfXVisPFWhEIv5AEQ0qcU8jmlDA2O4jc79Y/MsEyGYYc8UVVPSKORumfgKE124d3499up7D/Vg+qBP+wr6scTmU=,iv:OHdyMSopzwS6h6xsOMadPrSUSN7XSULPhYHPHrEvCMY=,tag:x6IwZVUpgDN6Thm18e9PnQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
