spotify-client-id: ENC[AES256_GCM,data:tAmqs7D+gmT7HK5UIZCs0QFEW6Pol6Ii2XifJPAmge0=,iv:LRfq3zCjSoKEB6NLMtshv3vKCktvVeqzqWDa1tmfDOk=,tag:6otNwLmd6hUhCB99lPL4/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5w53ch2ym5qmhew239j7qh0q0ax72daq42qvvwexferta2yrprsf4kes9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeWU5RXl1cFJCMCt0VG5S
            M0x5bDl6UUF3VWRWZDBTQzhIYTNZVU4rS0RFCkh3Tng1SGhqYkl4SER5eENYOXNH
            TFN1NmFoSDlQY3JrZ0dWaTBQZEFoQVEKLS0tIDQ0VmRkWGRMa2JGSWdHVml5cTZ3
            VjBXMkZiMFAwWUdtVHp3WFRqenJHakUKR4zWssrXy6iHMI8xgKX0l5+7LQ2yHJta
            c2UB/4RbWLxya/wM1mDmm2by25jMEqQnTg5JNFtdZUKde3EWuouJ4Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sg8swpg9vugyh4fuqlm2dmp9macsges4ehu3swn6evmudjpkaq8q239r53
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTVZuWnl6MGtmMGR0eGxU
            azlWaDlMWG1PRnFIclhtbCs4K1l6SjV3QUcwCnI3YUZ1eGlBUTZ5d0gxVkxPN0dt
            UTNSbnFURlB2UTNwUExDOUYvOWVUZ1UKLS0tIGljU3dEMXlQVVBRZTV2bEJGTU8z
            VTdxVXViSTFzS3RHS0xScnREalQ5UTgKnoq32kDhgZ9QRVQ7VGMNqJ1dao+9i6Pv
            pFdoHy3R9a1ibcvAK/EbUffUfuDVq7RxMiarHQvuSV00HhsazUwBhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-14T00:30:54Z"
    mac: ENC[AES256_GCM,data:Q5i0Fxii52vCpVWa9mYb5xDEhFfsXbS81dm+xMel+xkQOdMXsbgUew83PYRAYt6vpkCiBxFoOs40RkZuToIMtamOJgQe/qCcKmTlO4xFCH65UPRyBbBQCrCD8QnfpU7NR5dJkOeiQGu4w+lWsDUtZY/GMMOwsrTy8xzKaTuZ53s=,iv:vdHvu8euG3ww5DCaGkQbWAl+rOt1QQGnAB4SfWSv38E=,tag:CUImotblXrNB/Jn0naHb7w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
