spotify-client-id: ENC[AES256_GCM,data:LeoySdew/3xseoi5CRN1zLgz7zZLhcMB6P+CQclDfA8=,iv:+gIrj9qLBx95AOcsVxVEEq2Pe7kH/lSoU+A8scXWx58=,tag:n7E5DrNrKZl0KjR8OICoIQ==,type:str]
age-key: ENC[AES256_GCM,data:d+5fLhPcX+36YTolLCjEC8+3S8X5L8PEjytD3R3/MS7EVr17gMm4z0rnNBgPS7w4WTxw0o96071kYlS3uOoKq0L5SLMOC0TT2gcaqVlANdsmSV1E3ae4P9bws8Bv2mSMwK38WDmKqRKs6Y6MKPy4V27O/KuvkIdPbwHjupoyFxBSEmTmtjJSQN/GI3+4y2pKtEi0S/7TgQjOg3NpjsIY/4xlDCEUXiN+S7A5z0xKOLZyvE8z9z8t0sMP2sw=,iv:ANy5lrIHittpufM1+CQlZOyJF53QPnVLFxGKPn0Cdcc=,tag:OFGh3moYbZzjiNiHWfBMvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5w53ch2ym5qmhew239j7qh0q0ax72daq42qvvwexferta2yrprsf4kes9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdmtOWDhKcGs3a3hXZ0FF
            am1QUCtCbU1GbjBnM21UZXo1d0taQjd2N2kwClEySTg3bTEvcVd4RWhYOE9yVGxO
            L3VLTVMvVU01ZUpOMTRmRTVpczFsMncKLS0tIHFFa090bk9UV3VSL1VIWUtldkZo
            cFdKd3cwd0lGM0hud0dxaTFQeVpGdHMKmvl+TIAzjohDObSFJU7PmjRxR7HfvjEt
            ic5ZKiQTEOAby8WVLece83crWyx5cRszu4ZFF4mOsbCwZIuXVDilrQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hyzjxh89pjdfpuu9dz5wkk8t2zq8renv0kwqjlxcnrm5zze9udtsyu2knl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySjF6eDlMTVp5MTBWVnJZ
            L3pETEtIMmtpM2JvUFEwMFk5RU14ZlVQM25vCmtTeTRhZzFrMXE5bXRHWWhqdE5z
            cStnTUNQK1ZiU3NqOFRwU0tUdkM3TVEKLS0tIHk3S0h2QUIvUlQ0MUNyRGhzL1U0
            VDF6NDdLd3hnR3p4TkNUUlNYblZOS0UKdrbcwzpUx+/ABYpXGalepHuwrD6SLfl+
            ASebIiM5EubcE05df8Qd4ey6ZevpFJcyH5LNMyiWu3DoX+n/PMRwtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-05T12:34:27Z"
    mac: ENC[AES256_GCM,data:xN8X+Rbm+G8HmpIjwlHL23YPtluQcugWB+R82AKvwgITYaArZ4TPPRfGLssR8Y6XZ0bD724SZF5YcKd/RKKVIhiVbVmmB/3baVvLnSHeOOVsWiM5XLYIbWOKCXAE7OHUWJWUPjjDXK0KZR3TZq0DXvmAKEY+xOUGP3IJhrIkR2s=,iv:YGcbAgQPf7i1Cqvb6MX8YX8jqWyCi+3wUApxDaFBKzk=,tag:JZ1/DmjbVP+lsUjmHDoRgw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
