spotify-client-id: ENC[AES256_GCM,data:GpsEkBYWfecb0FtX4SEmvknC7clAqOpYK7LHfqPcB40=,iv:LGkRQyIF5xQpiL6NRE6Zxpak3um9QfqafPhX2vH13N0=,tag:M6+nqOQ0YnvLtwO3nJPXAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5w53ch2ym5qmhew239j7qh0q0ax72daq42qvvwexferta2yrprsf4kes9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRXNISlU3d3E1VkQySkJT
            R1Z6SlVBUGtKMkswemVHTWdFSGk2emFjMDIwCnJnOUtobmg3STBVQ3lqZnJ1MGEy
            N2Zxcm5FV1l4TTBvRVdONmM4TjZoK3cKLS0tIHRnTVRMdVoyY0d1cFJ0YjBxaEhY
            aDZSdTl0T0twZzVCdzBhSE5iZ0N4bm8KJjYzUqbeiomkLqWkri7IITonQrCjJhQD
            j6mI759wDk51OiG9cy/5uexWw8e3iqoUPqpGpOjTvnPy1Mo1qdaQfQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f6yc0z336wkj0ac0qhak2u2t5wqaksf8hpgxvn2mtas26hwk5gasx0th2l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0QWR3V0Y1SU0xN3Bwa05T
            YUs3a2tsU1JaRjllY1NBcVZZVFluMlJtd3dnClZHRGZUMUlJL2NHUnBNSWNOa1p4
            algzd1VndDFzY0dBTk1aVVdJWXhYeWMKLS0tIENMRm1YTWVIbFYzUnByOWJ5Smkw
            YVFXaEZERm9FUndSWEV6WVMxb0FEKzgKDVD2PWT4+F/mkfvNggzEN6i3aKbTIiYi
            hWz451K1dGJk0sWKlR5ti+MJIwo86/BLoN/JJISgxqIM+JQMjir4vA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17um38qhvjkseq3vly7hfuetut5af2nc9va8l2004vgyfkn3sdy8sszkqv0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRHlPMThQeUlXaDdqZDhv
            bEJnYUpQR3I5UFBRUVRnVnVWZ2tZMTdVQWtnCk0rRkF4UXRzUUhsdzNaRUJIVXYy
            R0RaNFdPbUhybWJObGFOcDlNUWl3dUEKLS0tIEQzbWplY2xiREUwbWtVUVJHWmhJ
            Mzk3Tm80SVYrOG5aeUMyWFpxZmQ0eGMK44NTsmLuZbrTlT+mGR3dd6Qh53s139mZ
            CjycgydCmJr+QAohMRpVl+wqgQhHu++G5NdPfhuwFSGR7vrFRXPKDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-13T00:06:45Z"
    mac: ENC[AES256_GCM,data:y/1iuEyMt62xQvGh3oLocr9bxXnsEAt6N2rBQrxBPjf3m2M88i3VDVcI6J2tShehObRceuEGyJlrN5iblNC3NM+WWVYbQX8tN/2ef+ZP7QET9YYyyqEnB78R2RIboJdIARXvrKH2yjGJPzJDkCHOu5CV05hz9BOSxIdUoIiNmFQ=,iv:YsEwzQ2NHzaP539/gcPALnSt6jafoEfMdupD9I4jLrU=,tag:omq8ltFzsvnQXMHMFANAiA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
