spotify-client-id: ENC[AES256_GCM,data:0KEpfe4bbr8CHAySJkI5j1NC7J8zWfNgI2L6ooxSidg=,iv:OX7x7gILGf2LX1t98pHxdfTzW83M50wrlj9TODAUMvw=,tag:rvDVPm9g3zJaI9chEtEBvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5w53ch2ym5qmhew239j7qh0q0ax72daq42qvvwexferta2yrprsf4kes9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWmExUDY2NmV2YmxXd0xp
            b0FaaDFGdTdvOXJieWxmdXBtbi9RM25IRUgwClBxSEk4b1dmaVpFSTJRbnRvUUE5
            NE1kSlpKZmNoQVF6S2Z4aEtPZ2RCeE0KLS0tIGp0QUtSS1RiWUtzUFhyYVhXUTdN
            UkxnTU5ldVgza1VlVlBXVkRxRjRmeUkKuMJfcRKyi5URd7FpaqtDUILMnv9+5u0U
            wTK4qIoGKWF1htwnEazX2Abk1e7cuSdTWRj6N0TvA9OeBaqeGLkQbA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17um38qhvjkseq3vly7hfuetut5af2nc9va8l2004vgyfkn3sdy8sszkqv0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUkttZGlkcnRQVVJpU0tn
            aFcvcnUxbFJaS29aUDErZGxXOGhSYmhCMEVrCnRiZzRObHl6WGZqOGpDY2lYaHds
            TmQ3R2dGSGVIY25kYXFyZEtFd0ZyQmMKLS0tIFh6OHhsSUtseTlLM3BuQmtJbUcv
            bVg2RGVHYk9sTjRYSzJSQTU2dnFINGMKmeNX/dt9hHhhRcwbJ27Tr1EWmnfaB9l7
            b+fur5XtIHju45v2hc+zNxKvy0XeFUfBMjKnzeyVjWpMJVpnOcEeYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-13T21:20:06Z"
    mac: ENC[AES256_GCM,data:5braf+TQ2vopRtxsv53X+SWzBRE0yG3FUDuynJVgIDWDmdQSQAgbGJvizcE4qGMmtulosGkIPMIQln1uRSkVHD2shdlgtaWe1cNiSAhQuuCNAxWLP15ScoNLbhkRRamNyVDwH/FH5wi+A4bQ1fRe44lOLPoVZTsv62hGB0mIL3M=,iv:kyEete2GGgtO4ZN5sItEqc9NncnPDV9yPwVkwU6IUp4=,tag:R4HhawcJQQX2NeJFbdYRhg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
