spotify-client-id: ENC[AES256_GCM,data:ruqG7JOP5cZDZPvDbetqS7eZ6FeWhOXp3yJ22H01+tU=,iv:1lwFV8tcstu5bjBLCwBTol6fOrSZ2Bsd5WmiPu8xyGs=,tag:wB/aVskTcE2esiyd3iSdpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5w53ch2ym5qmhew239j7qh0q0ax72daq42qvvwexferta2yrprsf4kes9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcXRCM01DWWwvQlRzbTNM
            bTFMSUdzV1JXYThCTGZ6Y1hHVytLR1M1ajJRCnV1M28wVFNJZlp4N2FtbUNqK2xK
            ZmtEK2d5bDltVkwvSzF0VlNoMkppcHcKLS0tIDllU3kyZEdEYjdQN1NEMzJkek9C
            QzlGOHFONTBoQnVrS01XWVZPMVNkTzgKHj2lhr+eE9EBDmU2tYH5jYa7ZjLM0b1/
            Plk/rZsxPanZg6FoJF4QW1V+XvjFVYmBTM4yj0SiWhHAMaJTUGczyw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17um38qhvjkseq3vly7hfuetut5af2nc9va8l2004vgyfkn3sdy8sszkqv0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RndCL1JkbHNBWWJ5THVN
            RU84OG01dXV6UmVIVnN0L1prT1ZxMUxEMEdVCkZrcVRkTWFqcThxQkJ6Yk5rcWJS
            ZVBObHFUclQ1QlgrWnp6UXJUOE92K0EKLS0tIGZLaWV2MEMxaXRIUVYvdkdPQ3VE
            dU9scGthNkJHQjRHNk1SVmkzQzJkMTgK3X4bKbVY3cUNk0BoiwgL2FZFGkJVjnF/
            O0zoal/DCKOFt72HVbSpSQQfpItpNT/FzLtOGqpHGIXZnIw3ZDjBbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-14T00:30:53Z"
    mac: ENC[AES256_GCM,data:J0r0Zm+y6KmRojrQq6mrmipwj6ZPOc3jnMBY6+5Nd2l7JqlwpsgPM2GRIq/cJ+f2Ng8Xw6T6BY609EEIdT2sek2lXTjDUHsqP2Day0xTlUW9AwggoCRb5eYOLdTZET8XLuU1qqGKKauK2qyJfF1gM/q+CJMqRgtY/m+rpR+7+3k=,iv:TMMX/mQoAtVsUcxqqBW7th6tDAexj6O9Jtd6Fyz9Q9M=,tag:FQjC6UfdvHfKQwLGXoArjw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
